 # PSY 763 week 3
 
This week we will:

1. Learn how matrix multiplications (and array methods) work in python
1. Generate data based on multiple categorical predictors
1. 

## Basic python concepts we will use this week:

1. Lists
1. Arrays
1. Definition of arrays using: `np.array()`, `np.zeros()`, `np.ones()`, `np.random.rand()`, `np.random.randn()`
1. Calling array methods
1. For loops

### 1. Lists

In [16]:
# This is a list. It has four elements. 
a = [1, 2, 6, 9]
# display the list:
print(a)

[1, 2, 6, 9]


A list is a general python structure, and can be used in many contexts. A list can hold strings, numbers, other lists - (nearly) anything you want. For example, a list can hold users of a website:

```python
users = ['bsmith', 'jdoe', 'sramonycajal']
```

This means it's a bad idea to try to do math on a list. Multiplication expands the number of items in a list:

In [18]:
# This repeats the list 3 times rather than multiplying the elements by 3
test_list = [1, 9, 3]
print(test_list * 3)

[1, 9, 3, 1, 9, 3, 1, 9, 3]


In [20]:
# Lists can be used for loops
test_list = [3, 7, 9]
for t in test_list:
    print('next list element is', t)

next list element is 3
next list element is 7
next list element is 9


### 2. Arrays
Arrays are the main type of variable you will use in numpy, and are designed for doing math. 

In [22]:
# The simplest way to define an array is to make a list of the values you want in it.
# the input to np.array is a list:
a_list = [1, 2, 3]
a = np.array(a_list)
# ... but you can condense these two steps to one, thus:
b = np.array([4, 5, 6])
# When printed, these look like lists...
print(a)
print(b)
# ... but they're not!

[1 2 3]
[4 5 6]


In [23]:
# arrays can be multiplied by scalars (constants)
print('a * 3 =')
print(a * 3)
# Elementwise multiplication
print('a * b = ')
print(a * b)

a * 3 =
[3 6 9]
a * b = 
[ 4 10 18]


In [24]:
# Arrays can be 2D as well. Notice that the input to np.array() here is a list of lists
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [37]:
# You can get the shape of an array using:
print('shape of c is :', np.shape(c))
# This is just like matlab's `size()` function

shape of c is : (2, 3)


In [39]:
# You can also get the shape of an array by accessing the shape *property* of the array:
print('shape of c is: ', c.shape)

shape of c is :  (2, 3)


Arrays (and lists!) have both *properties* and *methods* associated with them. These can be accessed with the following syntax:

In [34]:
# a is an array; `shape` is a property of an array (this is just like matlab's size() function)
print(a.shape)
print(c.shape)

(3,)
(2, 3)


[[1 2 3]
 [4 5 6]]


# Simple matrix multiplications

# These are like multiplying results and adding up products

# What is the identity matrix?

In [ ]:
a = np.array([])

In [3]:
# Matrix Inverses

In [4]:
import numpy as np

In [5]:
X = np.random.randn(10,3)

In [6]:
X

array([[ 0.4076584 , -0.05519555, -1.09129477],
       [-0.14774111, -1.25339242,  0.02747861],
       [-0.76774853, -0.20413684, -0.67692952],
       [ 1.44538544, -1.59724369,  0.47879231],
       [ 0.07638661, -0.3198899 , -0.40397661],
       [ 0.17441074,  1.78818343,  0.28447882],
       [ 1.43733003, -1.21759471, -1.0502065 ],
       [ 0.10695358, -0.28110062,  1.34302765],
       [ 0.50678588,  0.51152526,  0.56840818],
       [ 0.54126398,  0.74758058,  0.96358573]])

In [13]:
xTx = X.T.dot(X)

In [14]:
np.linalg.inv(xTx).dot(xTx)

array([[  1.00000000e+00,   7.21170192e-17,  -7.05434952e-18],
       [  7.97913188e-17,   1.00000000e+00,  -1.78319154e-17],
       [  9.35392397e-18,  -3.01958566e-17,   1.00000000e+00]])